Repository UMC-README/back-end, pull requests merged in 2024-08, with the labels that each got.

#72 공지글별 댓글 조회 기능 구현
  domains/room/room.controller.js
  domains/room/room.dao.js
  domains/room/room.dto.js
  domains/room/room.service.js
  domains/room/room.sql.js
  routes/room.route.js
  swagger/room.swagger.yaml
Labels: 🎉 FEAT

#82 [feat] 댓글 작성 기능 구현
  domains/room/room.controller.js
  domains/room/room.dao.js
  domains/room/room.service.js
  domains/room/room.sql.js
  routes/room.route.js
  swagger/room.swagger.yaml
Labels: 🎉 FEAT

#90 [feat] 토큰 구분 로직 구현
  middleware/token.auth.js
  utils/kakao.js
Labels: 🎉 FEAT

#85 [feat] 댓글 삭제 기능 구현
  domains/room/room.controller.js
  domains/room/room.dao.js
  domains/room/room.service.js
  domains/room/room.sql.js
  routes/room.route.js
  swagger/room.swagger.yaml
Labels: 🎉 FEAT

#88 [fix] 공지방 생성, url 생성 구현 및 응답 body 수정 및 swagger 추가
  domains/admin/admin.controller.js
  domains/admin/admin.dao.js
  domains/admin/admin.dto.js
  domains/admin/admin.service.js
  domains/admin/uuid.js
  swagger/admin.swagger.yaml
  swagger/swagger.config.js
Labels: 🐞 FIX

#100 [fix] 공지방 수정 응답 바디 수정 및 로직 변경
  domains/admin/admin.service.js
Labels: 🐞 FIX

#102 [refactor] 공지방 삭제 응답 바디 수정 및 로직 일부 수정
  domains/admin/admin.controller.js
  domains/admin/admin.dao.js
  domains/admin/admin.service.js
Labels: 🔨 REFACTOR

#93 [fix] iOS 카카오 로그인 로직 수정
  domains/user/user.controller.js
Labels: 🐞 FIX

#111 [chore] 공지방 수정, 삭제 & 공지글 생성, 수정, 삭제 swagger 작성
  swagger/admin.swagger.yaml
Labels: ⚙️ CHORE

#106 [refactor] 내가 개설한/입장한 공지방 조회 로직 수정
  domains/user/user.dao.js
  domains/user/user.sql.js
Labels: 🔨 REFACTOR

#108 [refactor] 공지글 생성 & 수정 & 삭제 응답 바디 형식 수정 및 dao, dto, serivce 일부 로직 수정
  domains/admin/admin.dao.js
  domains/admin/admin.dto.js
  domains/admin/admin.service.js
Labels: 🔨 REFACTOR

#115 [fix] 내가 생성한 공지방 & 내가 입장한 공지방 조회 기능 오류 수정
  domains/user/user.service.js
Labels: 🐞 FIX

#112 [feat] 제출 (공지 확인) 기능 구현
  domains/room/room.controller.js
  domains/room/room.dao.js
  domains/room/room.service.js
  domains/room/room.sql.js
  routes/room.route.js
  swagger/room.swagger.yaml
Labels: 🎉 FEAT

#118 [refactor] 유저 프로필 조회 바디 수정 및 swagger 추가
  domains/admin/admin.controller.js
  domains/admin/admin.dao.js
  domains/admin/admin.service.js
  domains/admin/admin.sql.js
  routes/admin.route.js
  swagger/admin.swagger.yaml
Labels: ⚙️ CHORE, 🔨 REFACTOR

#120 [refactor] 내가 개설한 공지방 조회 및 내가 입장한 공지방 조회 시의 리턴 값 수정
  domains/user/user.controller.js
  domains/user/user.dao.js
  domains/user/user.service.js
  domains/user/user.sql.js
  routes/user.route.js
  utils/elapsedTime.js
Labels: 🔨 REFACTOR

#116 [feat] 공지방별 프로필 수정 기능 구현
  domains/user/user.dao.js
  domains/user/user.sql.js
Labels: 🎉 FEAT

#123 [fix] 공지방 내 공지글 등 존재하지 않을 경우 예외 처리 구현
  domains/room/room.dao.js
  domains/room/room.dto.js
  domains/room/room.service.js
Labels: 🐞 FIX

#125 [chore] 작성되지 않았던 API에 대한 Swagger 작성
  domains/user/user.dao.js
  domains/user/user.service.js
  domains/user/user.sql.js
  swagger/user.swagger.yaml
  utils/timeChange.js
Labels: ⚙️ CHORE

#128 [fix] 커서 페이징 관련 Swagger 수정 및 오류 수정
  domains/room/room.dao.js
  domains/room/room.sql.js
  swagger/room.swagger.yaml
Labels: 🐞 FIX

#130 [feat] 유저 추방하기 구현
  domains/admin/admin.controller.js
  domains/admin/admin.dao.js
  domains/admin/admin.service.js
  domains/admin/admin.sql.js
  routes/admin.route.js
Labels: 🎉 FEAT

#129 dev -> main 반영
  domains/admin/admin.controller.js
  domains/admin/admin.dao.js
  domains/admin/admin.dto.js
  domains/admin/admin.service.js
  domains/admin/admin.sql.js
  domains/admin/uuid.js
  domains/room/room.controller.js
  domains/room/room.dao.js
  domains/room/room.dto.js
  domains/room/room.service.js
  domains/room/room.sql.js
  domains/user/user.controller.js
  domains/user/user.dao.js
  domains/user/user.service.js
  domains/user/user.sql.js
  middleware/token.auth.js
  routes/admin.route.js
  routes/room.route.js
  routes/user.route.js
  swagger/admin.swagger.yaml
  swagger/room.swagger.yaml
  swagger/swagger.config.js
  swagger/user.swagger.yaml
  utils/kakao.js
  utils/timeChange.js
Labels: ⚙️ CHORE

#133 [fix] 공지방 메인 미확인 공지글 및 댓글 생성시간 기준으로 변경
  domains/room/room.dto.js
  domains/room/room.sql.js
  swagger/room.swagger.yaml
Labels: 🐞 FIX

#135 [feat] 공지방별 닉네임 중복 확인 기능 구현
  domains/user/user.controller.js
  domains/user/user.dao.js
  domains/user/user.service.js
  domains/user/user.sql.js
  routes/user.route.js
  swagger/user.swagger.yaml
Labels: 🎉 FEAT

#136 [feat] 공지방 초대되어 최초 입장 화면 구현
  domains/room/room.controller.js
  domains/room/room.dao.js
  domains/room/room.service.js
  domains/room/room.sql.js
  routes/room.route.js
  swagger/room.swagger.yaml
Labels: 🎉 FEAT

#139 [feat] 유저 검색(특정/전체) 구현
  domains/admin/admin.controller.js
  domains/admin/admin.dao.js
  domains/admin/admin.service.js
  domains/admin/admin.sql.js
  routes/admin.route.js
Labels: 🎉 FEAT

#140 [feat] 공지방 입장시 비밀번호 일치 확인 기능 구현
  domains/room/room.controller.js
  domains/room/room.dao.js
  domains/room/room.service.js
  domains/room/room.sql.js
  routes/room.route.js
  swagger/room.swagger.yaml
Labels: 🎉 FEAT

#142 [feat] 최근 공지글 목록 조회 기능 구현
  domains/user/user.controller.js
  domains/user/user.dao.js
  domains/user/user.service.js
  domains/user/user.sql.js
  routes/user.route.js
  swagger/user.swagger.yaml
Labels: 🎉 FEAT

#145 [feat] 공지방 입장 기능 구현
  domains/room/room.controller.js
  domains/room/room.dao.js
  domains/room/room.service.js
  domains/room/room.sql.js
  routes/room.route.js
  swagger/room.swagger.yaml
Labels: 🎉 FEAT

#148 [refactor] 내가 입장한 공지방 조회 시 리턴 값 수정
  domains/user/user.dao.js
  domains/user/user.service.js
  domains/user/user.sql.js
  swagger/user.swagger.yaml
Labels: 🔨 REFACTOR

#155 dev -> main 최신화
  domains/admin/admin.controller.js
  domains/admin/admin.dao.js
  domains/admin/admin.service.js
  domains/admin/admin.sql.js
  domains/room/room.controller.js
  domains/room/room.dao.js
  domains/room/room.dto.js
  domains/room/room.service.js
  domains/room/room.sql.js
  domains/user/user.controller.js
  domains/user/user.dao.js
  domains/user/user.service.js
  domains/user/user.sql.js
  routes/admin.route.js
  routes/room.route.js
  routes/user.route.js
  swagger/room.swagger.yaml
  swagger/user.swagger.yaml
Labels: ⚙️ CHORE

#156 [fix] 각종 조회시 리턴값 추가
  domains/room/room.dao.js
  domains/room/room.dto.js
  domains/room/room.sql.js
  swagger/room.swagger.yaml
Labels: 🐞 FIX

#158 [feat] 공지 미확인 유저 조회 구현
  domains/admin/admin.controller.js
  domains/admin/admin.dao.js
  domains/admin/admin.service.js
  domains/admin/admin.sql.js
  routes/admin.route.js
Labels: 🎉 FEAT

#162 [refactor] 유저 검색(특정/전체) 쿼리 파라미터 roomId 추가
  domains/admin/admin.controller.js
  domains/admin/admin.dao.js
  domains/admin/admin.service.js
  domains/admin/admin.sql.js
Labels: 🔨 REFACTOR

#163 [chore] 이때까지 작성 안한 swagger 작성
  swagger/admin.swagger.yaml
Labels: ⚙️ CHORE

#170 [fix] 각종 조회시 리턴값 수정
  domains/room/room.dao.js
  domains/room/room.dto.js
  domains/room/room.service.js
  domains/room/room.sql.js
  swagger/room.swagger.yaml
Labels: 🐞 FIX

#171 dev -> main 최신화
  domains/admin/admin.controller.js
  domains/admin/admin.dao.js
  domains/admin/admin.service.js
  domains/admin/admin.sql.js
  domains/room/room.dao.js
  domains/room/room.dto.js
  domains/room/room.service.js
  domains/room/room.sql.js
  routes/admin.route.js
  swagger/admin.swagger.yaml
  swagger/room.swagger.yaml
Labels: ⚙️ CHORE

#165 [refactor] 최근 공지 조회 및 입장한/개설한 공지방 조회 총페이지 수 리턴 추가
  domains/user/user.dao.js
  domains/user/user.service.js
  swagger/user.swagger.yaml
Labels: 🔨 REFACTOR

#173 [refactor] 배열 관련 변수 리턴 시 null이 아닌 빈배열 리턴하도록 수정
  domains/user/user.service.js
Labels: 🔨 REFACTOR

#175 [refactor] 공지방 생성 , 공지글 생성, 유저 프로필 조회 로직 일부 수정
  domains/admin/admin.controller.js
  domains/admin/admin.dao.js
  domains/admin/admin.service.js
  domains/admin/admin.sql.js
  routes/admin.route.js
  swagger/admin.swagger.yaml
Labels: 🔨 REFACTOR

#179 [fix] URL로 공지방 입장, 이미 입장된 공지방인지 여부 추가 등 수정
  domains/room/room.controller.js
  domains/room/room.dao.js
  domains/room/room.service.js
  domains/room/room.sql.js
  routes/room.route.js
  swagger/room.swagger.yaml
Labels: 🐞 FIX

#180 dev -> main 최신화
  domains/admin/admin.controller.js
  domains/admin/admin.dao.js
  domains/admin/admin.service.js
  domains/admin/admin.sql.js
  domains/room/room.controller.js
  domains/room/room.dao.js
  domains/room/room.service.js
  domains/room/room.sql.js
  domains/user/user.dao.js
  domains/user/user.service.js
  routes/admin.route.js
  routes/room.route.js
  swagger/admin.swagger.yaml
  swagger/room.swagger.yaml
  swagger/user.swagger.yaml
Labels: ⚙️ CHORE

#181 [feat] 공지방 내 검색 기능 구현
  domains/room/room.controller.js
  domains/room/room.dao.js
  domains/room/room.dto.js
  domains/room/room.service.js
  domains/room/room.sql.js
  routes/room.route.js
  swagger/room.swagger.yaml
Labels: 🎉 FEAT

#177 [feat] 패널티 부여 구현
  domains/admin/admin.controller.js
  domains/admin/admin.dao.js
  domains/admin/admin.service.js
  domains/admin/admin.sql.js
  index.js
  package.json
  routes/admin.route.js
  swagger/admin.swagger.yaml
Labels: 🎉 FEAT

#186 dev -> main 최신화
  domains/admin/admin.controller.js
  domains/admin/admin.dao.js
  domains/admin/admin.service.js
  domains/admin/admin.sql.js
  domains/room/room.controller.js
  domains/room/room.dao.js
  domains/room/room.dto.js
  domains/room/room.service.js
  domains/room/room.sql.js
  index.js
  package-lock.json
  package.json
  routes/admin.route.js
  routes/room.route.js
  swagger/admin.swagger.yaml
  swagger/room.swagger.yaml
  utils/.gitkeep
  utils/date.js
Labels: ⚙️ CHORE

#183 [feat] 공지방마다 페널티 내역 조회 기능 구현
  domains/user/user.controller.js
  domains/user/user.dao.js
  domains/user/user.service.js
  domains/user/user.sql.js
  routes/user.route.js
  utils/timeChange.js
Labels: 🎉 FEAT

#188 [fix] url 관련 수정 및 유저 검색 return 값 수정
  domains/admin/admin.controller.js
  domains/admin/admin.dao.js
  routes/admin.route.js
  swagger/admin.swagger.yaml
Labels: 🐞 FIX

#189 dev -> main 최신화
  domains/admin/admin.controller.js
  domains/admin/admin.dao.js
  domains/user/user.controller.js
  domains/user/user.dao.js
  domains/user/user.service.js
  domains/user/user.sql.js
  routes/admin.route.js
  routes/user.route.js
  swagger/admin.swagger.yaml
  utils/timeChange.js
Labels: ⚙️ CHORE

#191 [fix] 공지방마다 제출한 미션 내역 조회 및 페널티 내역 조회 리턴값 수정
  domains/user/user.controller.js
  domains/user/user.dao.js
  domains/user/user.service.js
  domains/user/user.sql.js
Labels: 🐞 FIX

#195 [fix] JWT 토큰 유효기간 연장
  utils/generateToken.js
Labels: 🐞 FIX

#196 dev -> main
  domains/user/user.controller.js
  domains/user/user.dao.js
  domains/user/user.service.js
  domains/user/user.sql.js
  swagger/user.swagger.yaml
  utils/generateToken.js
Labels: ⚙️ CHORE

#197 [feat] 확인 요청 내역 조회 구현
  domains/admin/admin.controller.js
  domains/admin/admin.dao.js
  domains/admin/admin.dto.js
  domains/admin/admin.service.js
  domains/admin/admin.sql.js
  routes/admin.route.js
  swagger/admin.swagger.yaml
Labels: 🎉 FEAT

#198 dev -> main
  domains/admin/admin.controller.js
  domains/admin/admin.dao.js
  domains/admin/admin.dto.js
  domains/admin/admin.service.js
  domains/admin/admin.sql.js
  routes/admin.route.js
  swagger/admin.swagger.yaml
Labels: ⚙️ CHORE

#199 [feat] 대기 중 요청 수락/거절 구현
  domains/admin/admin.controller.js
  domains/admin/admin.dao.js
  domains/admin/admin.service.js
  domains/admin/admin.sql.js
  routes/admin.route.js
  swagger/admin.swagger.yaml
Labels: 🎉 FEAT

#201 [fix] 페널티 부여 관련
  domains/admin/admin.controller.js
  domains/admin/admin.dao.js
  domains/admin/admin.service.js
  domains/admin/admin.sql.js
  domains/room/room.dto.js
  index.js
  routes/admin.route.js
  swagger/admin.swagger.yaml
  utils/date.js
Labels: 🐞 FIX

#204 dev -> main 최신화
  domains/admin/admin.controller.js
  domains/admin/admin.dao.js
  domains/admin/admin.service.js
  domains/admin/admin.sql.js
  domains/room/room.dto.js
  index.js
  routes/admin.route.js
  swagger/admin.swagger.yaml
  utils/date.js
Labels: ⚙️ CHORE

#205 [refactor] 공지방 생성, 수정, 확인 요청 조회 수정본
  domains/admin/admin.controller.js
  domains/admin/admin.dao.js
  domains/admin/admin.dto.js
  domains/admin/admin.service.js
  domains/admin/admin.sql.js
Labels: 🔨 REFACTOR

#207 dev -> main 최신화
  domains/admin/admin.controller.js
  domains/admin/admin.dao.js
  domains/admin/admin.dto.js
  domains/admin/admin.service.js
  domains/admin/admin.sql.js
Labels: ⚙️ CHORE

#209 [fix] S3에 이미지 여러개 업로드 하도록 수정
  domains/user/user.controller.js
  routes/user.route.js
  swagger/user.swagger.yaml
Labels: 🐞 FIX

#210 dev -> main
  domains/user/user.controller.js
  routes/user.route.js
  swagger/user.swagger.yaml
Labels: ⚙️ CHORE

#203 [feat] 공지방 입장시 받은 페널티 확인창 구현
  domains/room/room.controller.js
  domains/room/room.dao.js
  domains/room/room.dto.js
  domains/room/room.service.js
  domains/room/room.sql.js
  routes/room.route.js
  swagger/room.swagger.yaml
Labels: 🎉 FEAT

#213 [refactor] 확인 요청 내역 조회 응답 바디 수정
  domains/admin/admin.dto.js
  domains/admin/admin.sql.js
  swagger/admin.swagger.yaml
  swagger/room.swagger.yaml
Labels: 🔨 REFACTOR

#214 [refactor] 공지방 정보 관련 API 수정
  config/response.status.js
  domains/admin/admin.controller.js
  domains/admin/admin.dao.js
  domains/admin/admin.dto.js
  domains/admin/admin.service.js
  domains/admin/admin.sql.js
  package.json
  routes/admin.route.js
  routes/room.route.js
  swagger/admin.swagger.yaml
  swagger/room.swagger.yaml
  swagger/user.swagger.yaml
Labels: 🔨 REFACTOR

#215 dev -> main 최신화
  config/response.status.js
  domains/admin/admin.controller.js
  domains/admin/admin.dao.js
  domains/admin/admin.dto.js
  domains/admin/admin.service.js
  domains/admin/admin.sql.js
  domains/room/room.controller.js
  domains/room/room.dao.js
  domains/room/room.dto.js
  domains/room/room.service.js
  domains/room/room.sql.js
  package.json
  routes/admin.route.js
  routes/room.route.js
  swagger/admin.swagger.yaml
  swagger/room.swagger.yaml
  swagger/user.swagger.yaml
Labels: ⚙️ CHORE

#217 [feat] S3 이미지 삭제 기능 구현
  config/response.status.js
  domains/user/user.controller.js
  middleware/s3.js
  routes/user.route.js
  swagger/user.swagger.yaml
Labels: 🎉 FEAT

#219 [fix] 공지글 미확인한 사람 수 카운트 로직 변경 등
  domains/admin/admin.controller.js
  domains/admin/admin.dao.js
  domains/admin/admin.service.js
  domains/admin/admin.sql.js
  domains/room/room.dao.js
  domains/room/room.dto.js
  domains/room/room.sql.js
  routes/admin.route.js
  swagger/admin.swagger.yaml
Labels: 🐞 FIX

#222 [refactor] 공지방 생성 return값 수정 및 유저 강퇴하기 body userId로 변경
  domains/admin/admin.dao.js
  domains/admin/admin.dto.js
  domains/admin/admin.service.js
  domains/admin/admin.sql.js
  swagger/admin.swagger.yaml
Labels: 🔨 REFACTOR

#223 dev -> main 최신화
  domains/admin/admin.dao.js
  domains/admin/admin.dto.js
  domains/admin/admin.service.js
  domains/admin/admin.sql.js
  swagger/admin.swagger.yaml
Labels: ⚙️ CHORE

#225 [feat] 회원가입 시 프로필 사진을 지정하지 않으면 기본 이미지로 설정
  domains/room/room.dao.js
  domains/room/room.sql.js
  domains/user/user.dao.js
  domains/user/user.sql.js
Labels: 🎉 FEAT

#228 [refactor] 공지글 수정 api 바디 수정
  domains/admin/admin.dao.js
  domains/admin/admin.dto.js
  domains/admin/admin.service.js
  domains/admin/admin.sql.js
  swagger/admin.swagger.yaml
Labels: 🔨 REFACTOR

#229 [feat] 공지글 상세 조회 API 구현
  config/response.status.js
  domains/admin/admin.controller.js
  domains/admin/admin.dao.js
  domains/admin/admin.dto.js
  domains/admin/admin.service.js
  domains/admin/admin.sql.js
  routes/admin.route.js
  swagger/admin.swagger.yaml
  utils/kakao.js
Labels: 🎉 FEAT

#232 [chore] Swagger 수정 등
  middleware/s3.js
  swagger/room.swagger.yaml
Labels: ⚙️ CHORE

#233 [chore] swagger 수정
  domains/admin/admin.dao.js
  swagger/admin.swagger.yaml
Labels: ⚙️ CHORE

#234 [chore] 4096*4096
  middleware/s3.js
Labels: ⚙️ CHORE

#235 dev -> main 최신화
  domains/admin/admin.dao.js
  middleware/s3.js
  swagger/admin.swagger.yaml
  swagger/room.swagger.yaml
Labels: ⚙️ CHORE

#237 [fix] 공지글에 대한 확인 요청 내역 조회 시 DELETE 상태 이미지 리턴 제외
  domains/admin/admin.service.js
  domains/admin/admin.sql.js
Labels: 🐞 FIX

#240 chore: sql 오류 수정
  domains/admin/admin.sql.js
Labels: ⚙️ CHORE

#241 [fix] 최근 공지글 목록 조회 시 totalPages 값 오류 수정
  domains/user/user.dao.js
  domains/user/user.service.js
  domains/user/user.sql.js
  index.js
Labels: 🐞 FIX

#245 [fix] 최근 공지글 목록 조회 시 공지방 ID 및 이름 리턴 누락 추가 및 이미지 중복 리턴 수정
  domains/admin/admin.dao.js
  domains/admin/admin.sql.js
  domains/user/user.service.js
Labels: 🐞 FIX

#246 [fix] 기한 시작이 입장 전인지 여부 리턴 추가
  domains/room/room.dao.js
  domains/room/room.dto.js
  domains/room/room.sql.js
  swagger/room.swagger.yaml
Labels: 🐞 FIX

#247 [chore] main 최신화
  domains/admin/admin.dao.js
  domains/admin/admin.sql.js
  domains/room/room.dao.js
  domains/room/room.dto.js
  domains/room/room.sql.js
  domains/user/user.service.js
  swagger/room.swagger.yaml
Labels: ⚙️ CHORE

#249 [fix] 마이페이지 공지방마다 제출한 미션 내역 조회 시 제출 이미지 EXIST 상태만 리턴하도록 수정
  domains/user/user.sql.js
Labels: 🐞 FIX

#250 [chore] main 최신화
  domains/user/user.sql.js
Labels: ⚙️ CHORE

#253 [refactor] 내가 개설한 공지방 및 입장한 공지방 조회 시 시간순에 맞게 리턴하도록 수정
  domains/user/user.sql.js
Labels: 🔨 REFACTOR

#257 [fix] 내 프로필 전체 조회 리턴 개수 수정
  domains/user/user.controller.js
Labels: 🐞 FIX

#255 [refactor] 유저 검색 api 수정
  domains/admin/admin.controller.js
  domains/admin/admin.dao.js
  domains/admin/admin.dto.js
  domains/admin/admin.service.js
  domains/admin/admin.sql.js
  swagger/admin.swagger.yaml
Labels: 🔨 REFACTOR

#258 [chore] main 최신화
  domains/admin/admin.controller.js
  domains/admin/admin.dao.js
  domains/admin/admin.dto.js
  domains/admin/admin.service.js
  domains/admin/admin.sql.js
  domains/user/user.controller.js
  middleware/s3.js
  swagger/admin.swagger.yaml
Labels: ⚙️ CHORE

#260 [fix] 공지글 생성시 startDate 로직 수정
  domains/admin/admin.dao.js
  domains/room/room.dto.js
Labels: 🐞 FIX

#261 [chore] main 최신화
  domains/admin/admin.dao.js
  domains/room/room.dto.js
Labels: ⚙️ CHORE

#263 [chore] main 최신화
  domains/admin/admin.dao.js
  domains/admin/admin.sql.js
Labels: ⚙️ CHORE

#264 chore: 콘솔로그추가
  domains/admin/admin.service.js
Labels: ⚙️ CHORE

#265 [chore] main 최신화
  domains/admin/admin.dao.js
  domains/room/room.dto.js
Labels: ⚙️ CHORE
