Repository UMC-README/back-end, pull requests merged in 2024-07, with the labels that each got.

#8 [feat] 회원가입 기능 구현
  .gitignore
  config/db.config.js
  domains/.gitkeep
  domains/user/user.controller.js
  domains/user/user.dao.js
  domains/user/user.dto.js
  domains/user/user.service.js
  domains/user/user.sql.js
  index.js
  package-lock.json
  package.json
  routes/.gitkeep
  routes/user.route.js
Labels: 🎉 FEAT

#10 [feat] S3 코드 베이스 설정
  .prettierrc.json
  config/response.status.js
  domains/user/user.service.js
  index.js
  middleware/image.uploader.js
  middleware/uuid.js
  package-lock.json
  package.json
Labels: 🎉 FEAT

#14 [feat] 회원가입/로그인 JWT 토큰 발급 기능 구현
  config/response.status.js
  domains/user/user.service.js
  domains/user/user.sql.js
  middleware/token.auth.js
  utils/generateToken.js
  utils/passwordHash.js
Labels: 🎉 FEAT

#19 [feat] 이메일 인증 로직 구현
  config/response.status.js
  domains/user/user.controller.js
  package-lock.json
  package.json
  routes/user.route.js
  utils/email.js
Labels: 🎉 FEAT

#16 [feat] 내 프로필 조회 기능 구현
  domains/user/user.controller.js
  domains/user/user.service.js
  middleware/token.auth.js
  routes/user.route.js
Labels: 🎉 FEAT

#18 [feat] 고정된 공지글 조회 기능 구현
  domains/user/user.controller.js
  domains/user/user.dao.js
  domains/user/user.service.js
  domains/user/user.sql.js
  routes/user.route.js
Labels: 🎉 FEAT

#22 [feat] 내가 개설한 공지방 조회 기능 구현
  domains/user/user.controller.js
  domains/user/user.dao.js
  domains/user/user.service.js
  domains/user/user.sql.js
  routes/user.route.js
Labels: 🎉 FEAT

#26 [feat] 유저 프로필 조회 구현
  config/db.config.js
  domains/admin/admin.controller.js
  domains/admin/admin.dao.js
  domains/admin/admin.service.js
  domains/admin/admin.sql.js
  routes/admin.route.js
  swagger/admin.swagger.yaml
Labels: 🎉 FEAT

#27 고정 공지글 변경 및 삭제 구현
  config/db.config.js
  domains/room/room.controller.js
  domains/room/room.dao.js
  domains/room/room.service.js
  domains/room/room.sql.js
  index.js
  package-lock.json
  routes/room.route.js
  swagger/room.swagger.yaml
  swagger/swagger.config.js
Labels: 🎉 FEAT

#30 [chore] 배포 workflow 작성
  .github/workflows/deploy.yml
  swagger/swagger.config.js
Labels: ⚙️ CHORE

#31 [chore] workflow 테스트
  .github/ISSUE_TEMPLATE/issue-template.md
  .github/ISSUE_TEMPLATE/issue_template.md
  .github/pull_request_template.md
  .github/workflows/deploy.yml
  .gitignore
  .prettierrc.json
  config/db.config.js
  config/response.status.js
  domains/.gitkeep
  domains/admin/admin.controller.js
  domains/admin/admin.dao.js
  domains/admin/admin.service.js
  domains/admin/admin.sql.js
  domains/room/room.controller.js
  domains/room/room.dao.js
  domains/room/room.service.js
  domains/room/room.sql.js
  domains/user/user.controller.js
  domains/user/user.dao.js
  domains/user/user.dto.js
  domains/user/user.service.js
  domains/user/user.sql.js
  index.js
  middleware/image.uploader.js
  middleware/token.auth.js
  middleware/uuid.js
  package-lock.json
  package.json
  routes/.gitkeep
  routes/admin.route.js
  routes/room.route.js
  routes/user.route.js
  swagger/admin.swagger.yaml
  swagger/room.swagger.yaml
  swagger/swagger.config.js
  swagger/user.swagger.yaml
  utils/email.js
  utils/generateToken.js
  utils/passwordHash.js
Labels: ⚙️ CHORE

#32 [feat] 공지방 생성 구현
  config/db.config.js
  domains/admin/admin.controller.js
  domains/admin/admin.dao.js
  domains/admin/admin.service.js
  domains/admin/admin.sql.js
  index.js
  routes/admin.route.js
Labels: 🎉 FEAT

#34 [chore] 회원가입, 로그인 기능 swagger 작성
  swagger/user.swagger.yaml
Labels: ⚙️ CHORE

#36 [feat] 내가 입장한 공지방 조회 기능 구현
  domains/user/user.controller.js
  domains/user/user.dao.js
  domains/user/user.service.js
  domains/user/user.sql.js
  routes/user.route.js
  swagger/swagger.config.js
  swagger/user.swagger.yaml
Labels: 🎉 FEAT

#39 [hotfix] db.config.js 없는 오류 해결
  .gitignore
  config/db.config.js
Labels: 🐞 FIX

#37 [chore] 서버 배포를 위한 dev to main
  .gitignore
  config/db.config.js
  swagger/user.swagger.yaml
Labels: ⚙️ CHORE

#42 [chore] User Swagger 오류 수정 및 내가 생성한 공지방 조회 추가
  swagger/user.swagger.yaml
Labels: ⚙️ CHORE

#46 [feat] 내가 생성한 공지방 조회 및 내가 입장한 공지방 조회 Pagination 구현
  domains/user/user.controller.js
  domains/user/user.dao.js
  domains/user/user.service.js
  domains/user/user.sql.js
  routes/user.route.js
  swagger/user.swagger.yaml
Labels: 🎉 FEAT

#50 [feat] 카카오 로그인 기능 구현
  .github/workflows/deploy.yml
  domains/user/user.controller.js
  domains/user/user.service.js
  routes/user.route.js
  utils/kakao.js
Labels: 🎉 FEAT

#52 [feat] 공지방 내 모든 공지글 조회
  .gitignore
  domains/room/room.controller.js
  domains/room/room.dao.js
  domains/room/room.dto.js
  domains/room/room.service.js
  domains/room/room.sql.js
  routes/room.route.js
  swagger/room.swagger.yaml
Labels: 🎉 FEAT

#53 [feat] 공지방 수정 기능 구현
  domains/admin/admin.controller.js
  domains/admin/admin.dao.js
  domains/admin/admin.service.js
  domains/admin/admin.sql.js
  routes/admin.route.js
Labels: 🎉 FEAT

#58 [feat] 공지방 삭제 구현
  domains/admin/admin.controller.js
  domains/admin/admin.dao.js
  domains/admin/admin.service.js
  domains/admin/admin.sql.js
  routes/admin.route.js
Labels: 🎉 FEAT

#56 [feat] 내 프로필 전체 조회 기능 구현
  .DS_Store
  domains/user/user.controller.js
  domains/user/user.dao.js
  domains/user/user.service.js
  domains/user/user.sql.js
  routes/user.route.js
  swagger/user.swagger.yaml
Labels: 🎉 FEAT

#62 [feat] 공지방 내 완료하지 않은 공지글 조회 기능 구현
  domains/room/room.controller.js
  domains/room/room.dao.js
  domains/room/room.dto.js
  domains/room/room.service.js
  domains/room/room.sql.js
  routes/room.route.js
  swagger/room.swagger.yaml
Labels: 🎉 FEAT

#63 [feat] 내 비밀번호 확인 및 수정 기능 구현
  config/response.status.js
  domains/user/user.controller.js
  domains/user/user.dao.js
  domains/user/user.dto.js
  domains/user/user.service.js
  domains/user/user.sql.js
  routes/user.route.js
Labels: 🎉 FEAT

#66 fix : 공지방 삭제 Soft Delete로 로직 수정
  domains/admin/admin.service.js
  domains/admin/admin.sql.js
  routes/admin.route.js
Labels: 🐞 FIX

#68 [chore] dev -> main 반영
  .DS_Store
  .github/pull_request_template.md
  .github/workflows/deploy.yml
  .gitignore
  config/response.status.js
  domains/admin/admin.controller.js
  domains/admin/admin.dao.js
  domains/admin/admin.service.js
  domains/admin/admin.sql.js
  domains/room/room.controller.js
  domains/room/room.dao.js
  domains/room/room.dto.js
  domains/room/room.service.js
  domains/room/room.sql.js
  domains/user/user.controller.js
  domains/user/user.dao.js
  domains/user/user.dto.js
  domains/user/user.service.js
  domains/user/user.sql.js
  routes/admin.route.js
  routes/room.route.js
  routes/user.route.js
  swagger/room.swagger.yaml
  swagger/user.swagger.yaml
  utils/kakao.js
Labels: ⚙️ CHORE

#70 [feat] 개별 공지글 상세 조회 구현
  domains/room/room.controller.js
  domains/room/room.dao.js
  domains/room/room.dto.js
  domains/room/room.service.js
  domains/room/room.sql.js
  routes/room.route.js
  swagger/room.swagger.yaml
Labels: 🎉 FEAT

#75 [fix] 공지글 생성 unread_count 구현 방식 변경
  domains/admin/admin.dao.js
  domains/admin/admin.sql.js
Labels: 🐞 FIX

#79 [fix] 공지방 생성 sql, service, dao, controller 수정
  domains/admin/admin.controller.js
  domains/admin/admin.dao.js
  domains/admin/admin.service.js
  domains/admin/admin.sql.js
Labels: 🐞 FIX

#77 [feat] 공지글 수정 구현
  domains/admin/admin.controller.js
  domains/admin/admin.dao.js
  domains/admin/admin.service.js
  domains/admin/admin.sql.js
  routes/admin.route.js
Labels: 🎉 FEAT

#80 [feat] 공지글 삭제 구현
  domains/admin/admin.controller.js
  domains/admin/admin.dao.js
  domains/admin/admin.service.js
  domains/admin/admin.sql.js
  routes/admin.route.js
Labels: 🎉 FEAT
